  
version: '3'
services:
  node:
    restart: always
    build: 
      context: .
      dockerfile: "./classifier/Dockerfile"
    volumes:
      - ./classifier/dist:/app/dist
    ports:
      - "8080:8080"
  browser:
    tty: true
    build:
      context: .
      dockerfile: ./puppeteer/Dockerfile
    volumes:
      - "./puppeteer/:/app/"
      - "./output:/output"
    depends_on:
      - tor
      - node
  tor:
    build:
      context: .
      dockerfile: ./tor/Dockerfile
    expose:
      - "9150"