  
version: '3.7'
services:
  classifier:
    restart: always
    build: 
      context: .
      dockerfile: "./server/classifier/Dockerfile"
    volumes:
      - ./server/classifier/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - tor
  browser:
    tty: true
    build:
      context: .
      dockerfile: ./server/puppeteer/Dockerfile
    volumes:
      - "./server/puppeteer/src:/app/src"
      - "./server/puppeteer/assets:/app/assets"
      - "./output:/output"
    depends_on:
      - tor
      - classifier
    # command: node src/index.js
  tor:
    image: znetstar/tor-router
    container_name: tor-socks-proxy
    restart: always
    expose:
      - "9050"
    command: tor-router -s -d -j 10
