  
version: '3'
services:
  node:
    restart: always
    build: 
      context: .
      dockerfile: "./server/classifier/Dockerfile"
    volumes:
      - ./server/classifier/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - tor
  browser:
    tty: true
    build:
      context: .
      dockerfile: ./server/puppeteer/Dockerfile
    volumes:
      - "./server/puppeteer/:/app/"
      - "./output:/output"
    depends_on:
      - tor
      - node
  tor:
    build:
      context: ./server/tor
      dockerfile: ./Dockerfile
    volumes:
      - "./server/tor/torrc:/etc/tor/torrc"
    expose:
      - "9150"