  
version: '3.3'
services:
  classifier:
    restart: always
    image: necka/nsfw-classifier
    #build: 
    #  context: .
    #  dockerfile: "./server/classifier/Dockerfile"
    volumes:
      - ./server/classifier/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - tor
  browser:
    tty: true
    build:
      context: .
      dockerfile: ./server/puppeteer/Dockerfile
    ports: 
      - "8081:8080"
    volumes:
      - "./server/puppeteer/src:/app/src"
      - "./server/puppeteer/assets:/app/assets"
      - "./output:/output"
    depends_on:
      - tor
      - classifier
    # command: >
    #   sh -c "node src/index.js > src/browser.log &&
    #          websocketd --port=8080 tail -f src/browser.log"
  tor:
    image: dperson/torproxy
    container_name: tor-socks-proxy
    restart: always
    ports: 
      - "9050:9050"
      - "8118:8118"
    expose:
      - "9050"
